language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

install:
  - echo "Hello World!"
  - docker-compose -f ./docker-compose-build.yaml build --parallel

# this is a Travis CI config file for an exercise in using Travis to build 
# the 4 images.  As long as the docker-compose.build.yaml file refers to 
# the source code of the apps (with the context field), 
# in the directory tree structure as it appears on the GitHub udagram repo, 
# then the images can be built.  
# My repo has all node_modules dependencies and source code for the app, so 
# the images can be built.