version: "3"
services:
  reverseproxy:
    build:
      context: reverseproxy
    image: char2pie/reverseproxy 
  backend_user:
    build:
      context: udacity-c3-restapi-user
    image: char2pie/udagram-restapi-user
  backend_feed:
    build:
      context: udacity-c3-restapi-feed  
    image: char2pie/udagram-restapi-feed
  frontend:
    build:
      context: udacity-c3-frontend  
    image: char2pie/udacity-frontend

# Run docker-compose-build.yaml to build all four Docker images
# context tells where to find the Dockerfiles
