apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  selector:
    matchLabels:
      service: backend-feed
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1     # allow 1 extra replica during the update
      maxUnavailable: 0  # don't allow less than 1 replica
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      restartPolicy: Always 
      containers:
      - image: char2pie/udagram-restapi-feed
        name: backend-feed
        imagePullPolicy: Always
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: port
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        - name: ALLOW_ORIGIN_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: allow_origin_url
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION
        - name: POSTGRESS_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_DB
        - name: POSTGRESS_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRESS_HOST
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: postgress_password
        - name: POSTGRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: postgress_username    
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: jwt_secret
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_profile 
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_secret_access_key
        ports:
        - containerPort: 8080 
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        