apiVersion: v1
kind: Service
metadata: 
  name: frontend
  labels:
    service: frontend
spec:
  selector:
    service: frontend  # the pod labels that this service will serve
  type: NodePort
  ports:
  - nodePort: 31000  # the exposed port of the service
    port: 8100    # the service port inside the node (not the exposed port)
    targetPort: 80  # the port on the frontend pod
  
  